package br.com.gep.sped.fiscal.marshaller.writer;

import br.com.gep.sped.fiscal.marshaller.registros.bloco0.*;
import br.com.gep.sped.fiscal.marshaller.registros.bloco1.*;
import br.com.gep.sped.fiscal.marshaller.registros.bloco9.Reg9001;
import br.com.gep.sped.fiscal.marshaller.registros.bloco9.Reg9900;
import br.com.gep.sped.fiscal.marshaller.registros.bloco9.Reg9990;
import br.com.gep.sped.fiscal.marshaller.registros.bloco9.Reg9999;
import br.com.gep.sped.fiscal.marshaller.registros.blocoC.*;
import br.com.gep.sped.fiscal.marshaller.registros.blocoD.*;
import br.com.gep.sped.fiscal.marshaller.registros.blocoE.*;
import br.com.gep.sped.fiscal.marshaller.registros.blocoG.*;
import br.com.gep.sped.fiscal.marshaller.registros.blocoH.*;
import br.com.gep.sped.marshaller.common.writer.SpedWriterFactory;
import org.beanio.builder.StreamBuilder;

public class SpedFiscalWriterFactory extends SpedWriterFactory {

    private static volatile SpedWriterFactory instance;

    private SpedFiscalWriterFactory() {
        super("spedfiscal");
    }

    public static SpedWriterFactory getInstance() {
        if (instance == null) {
            synchronized (SpedFiscalWriterFactory.class) {
                if (instance == null) {
                    instance = new SpedFiscalWriterFactory()
                            .initializeFactory();
                }
            }
        }

        return instance;
    }

    @Override
    protected void addRecords(StreamBuilder builder) {
        builder
                .addRecord(Reg0000.class)
                .addRecord(Reg0001.class)
                .addRecord(Reg0005.class)
                .addRecord(Reg0015.class)
                .addRecord(Reg0100.class)
                .addRecord(Reg0150.class)
                .addRecord(Reg0175.class)
                .addRecord(Reg0190.class)
                .addRecord(Reg0200.class)
                .addRecord(Reg0205.class)
                .addRecord(Reg0206.class)
                .addRecord(Reg0220.class)
                .addRecord(Reg0300.class)
                .addRecord(Reg0305.class)
                .addRecord(Reg0400.class)
                .addRecord(Reg0450.class)
                .addRecord(Reg0460.class)
                .addRecord(Reg0500.class)
                .addRecord(Reg0600.class)
                .addRecord(Reg0990.class)
                .addRecord(RegC001.class)
                .addRecord(RegC100.class)
                .addRecord(RegC105.class)
                .addRecord(RegC110.class)
                .addRecord(RegC111.class)
                .addRecord(RegC112.class)
                .addRecord(RegC113.class)
                .addRecord(RegC114.class)
                .addRecord(RegC115.class)
                .addRecord(RegC116.class)
                .addRecord(RegC120.class)
                .addRecord(RegC130.class)
                .addRecord(RegC140.class)
                .addRecord(RegC141.class)
                .addRecord(RegC160.class)
                .addRecord(RegC165.class)
                .addRecord(RegC170.class)
                .addRecord(RegC171.class)
                .addRecord(RegC172.class)
                .addRecord(RegC173.class)
                .addRecord(RegC174.class)
                .addRecord(RegC175.class)
                .addRecord(RegC176.class)
                .addRecord(RegC177.class)
                .addRecord(RegC178.class)
                .addRecord(RegC179.class)
                .addRecord(RegC190.class)
                .addRecord(RegC195.class)
                .addRecord(RegC197.class)
                .addRecord(RegC300.class)
                .addRecord(RegC310.class)
                .addRecord(RegC320.class)
                .addRecord(RegC321.class)
                .addRecord(RegC350.class)
                .addRecord(RegC370.class)
                .addRecord(RegC390.class)
                .addRecord(RegC400.class)
                .addRecord(RegC405.class)
                .addRecord(RegC410.class)
                .addRecord(RegC420.class)
                .addRecord(RegC425.class)
                .addRecord(RegC460.class)
                .addRecord(RegC465.class)
                .addRecord(RegC470.class)
                .addRecord(RegC490.class)
                .addRecord(RegC500.class)
                .addRecord(RegC510.class)
                .addRecord(RegC590.class)
                .addRecord(RegC600.class)
                .addRecord(RegC601.class)
                .addRecord(RegC610.class)
                .addRecord(RegC690.class)
                .addRecord(RegC700.class)
                .addRecord(RegC790.class)
                .addRecord(RegC791.class)
                .addRecord(RegC800.class)
                .addRecord(RegC850.class)
                .addRecord(RegC860.class)
                .addRecord(RegC890.class)
                .addRecord(RegC990.class)
                .addRecord(RegD001.class)
                .addRecord(RegD100.class)
                .addRecord(RegD110.class)
                .addRecord(RegD120.class)
                .addRecord(RegD130.class)
                .addRecord(RegD140.class)
                .addRecord(RegD150.class)
                .addRecord(RegD160.class)
                .addRecord(RegD161.class)
                .addRecord(RegD162.class)
                .addRecord(RegD170.class)
                .addRecord(RegD180.class)
                .addRecord(RegD190.class)
                .addRecord(RegD195.class)
                .addRecord(RegD197.class)
                .addRecord(RegD300.class)
                .addRecord(RegD301.class)
                .addRecord(RegD310.class)
                .addRecord(RegD350.class)
                .addRecord(RegD355.class)
                .addRecord(RegD360.class)
                .addRecord(RegD365.class)
                .addRecord(RegD370.class)
                .addRecord(RegD390.class)
                .addRecord(RegD400.class)
                .addRecord(RegD410.class)
                .addRecord(RegD411.class)
                .addRecord(RegD420.class)
                .addRecord(RegD500.class)
                .addRecord(RegD510.class)
                .addRecord(RegD530.class)
                .addRecord(RegD590.class)
                .addRecord(RegD600.class)
                .addRecord(RegD610.class)
                .addRecord(RegD690.class)
                .addRecord(RegD695.class)
                .addRecord(RegD696.class)
                .addRecord(RegD697.class)
                .addRecord(RegD990.class)
                .addRecord(RegE001.class)
                .addRecord(RegE100.class)
                .addRecord(RegE110.class)
                .addRecord(RegE111.class)
                .addRecord(RegE112.class)
                .addRecord(RegE113.class)
                .addRecord(RegE115.class)
                .addRecord(RegE116.class)
                .addRecord(RegE200.class)
                .addRecord(RegE210.class)
                .addRecord(RegE220.class)
                .addRecord(RegE230.class)
                .addRecord(RegE240.class)
                .addRecord(RegE250.class)
                .addRecord(RegE500.class)
                .addRecord(RegE510.class)
                .addRecord(RegE520.class)
                .addRecord(RegE530.class)
                .addRecord(RegE990.class)
                .addRecord(RegG001.class)
                .addRecord(RegG110.class)
                .addRecord(RegG125.class)
                .addRecord(RegG126.class)
                .addRecord(RegG130.class)
                .addRecord(RegG140.class)
                .addRecord(RegG990.class)
                .addRecord(RegH001.class)
                .addRecord(RegH005.class)
                .addRecord(RegH010.class)
                .addRecord(RegH020.class)
                .addRecord(RegH990.class)
                .addRecord(Reg1001.class)
                .addRecord(Reg1010.class)
                .addRecord(Reg1100.class)
                .addRecord(Reg1105.class)
                .addRecord(Reg1110.class)
                .addRecord(Reg1200.class)
                .addRecord(Reg1210.class)
                .addRecord(Reg1300.class)
                .addRecord(Reg1310.class)
                .addRecord(Reg1320.class)
                .addRecord(Reg1350.class)
                .addRecord(Reg1360.class)
                .addRecord(Reg1370.class)
                .addRecord(Reg1390.class)
                .addRecord(Reg1391.class)
                .addRecord(Reg1400.class)
                .addRecord(Reg1500.class)
                .addRecord(Reg1510.class)
                .addRecord(Reg1600.class)
                .addRecord(Reg1700.class)
                .addRecord(Reg1710.class)
                .addRecord(Reg1800.class)
                .addRecord(Reg1900.class)
                .addRecord(Reg1910.class)
                .addRecord(Reg1920.class)
                .addRecord(Reg1921.class)
                .addRecord(Reg1922.class)
                .addRecord(Reg1923.class)
                .addRecord(Reg1925.class)
                .addRecord(Reg1926.class)
                .addRecord(Reg1990.class)
                .addRecord(Reg9001.class)
                .addRecord(Reg9900.class)
                .addRecord(Reg9990.class)
                .addRecord(Reg9999.class);
    }
}
