CREATE TABLE IF NOT EXISTS BATCH_SPED_EXECUTION (
  ID BIGINT NOT NULL PRIMARY KEY,
  CNPJ CHARACTER VARYING(14) NOT NULL,
  NOME CHARACTER VARYING(100),
  ANO INTEGER NOT NULL,
  MES INTEGER NOT NULL,
  ARQUIVO CHARACTER VARYING(255),
  LAYOUT CHARACTER VARYING(15),
  JOB_EXECUTION_ID BIGINT NOT NULL,
  CONSTRAINT BATCH_SPED_JOB_FKEY FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE SEQUENCE BATCH_SPED_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;